### ISSUE TITLE
No Hidden->Hidden NAC Works Better

### ISSUE THREAD

**Issue by iamtrask** [a7b23/NALU#1]
I ran experiments where NAC/NALU was used as a hidden-to-hidden layer (as you have implemented) as well as experiments where the hidden -> hidden was purely additive (each NAC simply added/subtracted into the next hidden state).  Both work, but the latter works much better.

**Comment by iamtrask** [comment]
(And the latter is the one we used in the paper. Basically, most use cases just needed the hidden->hidden to learn the identity function which makes it not really worth learning)

**Comment by a7b23** [comment]
Hi @iamtrask, thanks a lot for your suggestions. I have incorporated the changes suggested by you and am getting the desired results now!!
